### PR TITLE
fix readthedocs compilation

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
Similarly as in:
https://github.com/SeisSol/SeisSol/pull/853

### CODE REVIEW

**Comment by AliceGabriel** [comment]
@dmay23 can you review this PR please?

**Comment by AliceGabriel** [comment]
Looks good to me, this update is due to release of urllib3 2.0 on May 4th

**Comment by Thomas-Ulrich** [comment]
This is  what Carsten wrote:
> Read the docs was broken for SeisSol, too, due to the release of urllib3 v2. You can add “urllib3<2” to docs/requirements.txt, then read the docs should build again. See https://github.com/SeisSol/SeisSol/pull/853

**Comment by dmay23** [comment]
@Thomas-Ulrich If there are any immediate additional Spack related changes you need to make, please re-open this PR, or PR #44 and make the changes there.

**Pull request merged**
